# Generated by Django 2.1 on 2019-02-21 18:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
        ('cashback_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.Preferences')),
                ('start_message', models.TextField(default='-', verbose_name='Сообщение при запуске')),
            ],
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
    ]
