# Generated by Django 2.1 on 2019-02-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback_app', '0002_texts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='texts',
            options={'verbose_name': 'тексты', 'verbose_name_plural': 'тексты'},
        ),
        migrations.RemoveField(
            model_name='texts',
            name='start_message',
        ),
        migrations.AddField(
            model_name='texts',
            name='start_message_0',
            field=models.TextField(default='-', verbose_name='Сообщение при запуске1'),
        ),
        migrations.AddField(
            model_name='texts',
            name='start_message_1',
            field=models.TextField(default='-', verbose_name='Сообщение при запуске2'),
        ),
        migrations.AddField(
            model_name='texts',
            name='start_message_2',
            field=models.TextField(default='-', verbose_name='Сообщение при запуске3'),
        ),
        migrations.AddField(
            model_name='texts',
            name='start_message_3',
            field=models.TextField(default='-', verbose_name='Сообщение при запуске4'),
        ),
    ]
