# Generated by Django 2.1 on 2019-02-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback_app', '0003_auto_20190221_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='start_message_0',
            field=models.TextField(default='-', verbose_name='Сообщение при запуске 1'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='start_message_1',
            field=models.TextField(default='-', verbose_name='Сообщение при запуске 2'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='start_message_2',
            field=models.TextField(default='-', verbose_name='Сообщение при запуске 3'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='start_message_3',
            field=models.TextField(default='-', verbose_name='Сообщение при запуске 4'),
        ),
    ]
