# Generated by Django 2.1 on 2019-02-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback_app', '0006_auto_20190221_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='help_message',
            field=models.TextField(default='-', verbose_name='Cообщение'),
        ),
    ]
