# Generated by Django 2.1 on 2019-02-26 09:25

import cashback_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback_app', '0013_auto_20190222_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='search_button',
            field=models.CharField(default='-', max_length=256, verbose_name='Надпись на кнопке: '),
        ),
        migrations.AddField(
            model_name='texts',
            name='search_message',
            field=models.TextField(default='-', verbose_name='Сообщение: '),
        ),
        migrations.AlterField(
            model_name='texts',
            name='help_message',
            field=models.TextField(default='-', verbose_name='Cообщение: '),
        ),
        migrations.AlterField(
            model_name='texts',
            name='start_photo_0',
            field=cashback_app.models.Photo(blank=True, null=True, upload_to=cashback_app.models.Photo.get_path, validators=[cashback_app.models.Photo.validate_image], verbose_name='Фото #1'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='start_photo_1',
            field=cashback_app.models.Photo(blank=True, null=True, upload_to=cashback_app.models.Photo.get_path, validators=[cashback_app.models.Photo.validate_image], verbose_name='Фото #2'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='start_photo_2',
            field=cashback_app.models.Photo(blank=True, null=True, upload_to=cashback_app.models.Photo.get_path, validators=[cashback_app.models.Photo.validate_image], verbose_name='Фото #3'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='start_photo_3',
            field=cashback_app.models.Photo(blank=True, null=True, upload_to=cashback_app.models.Photo.get_path, validators=[cashback_app.models.Photo.validate_image], verbose_name='Фото #4'),
        ),
    ]
