# Generated by Django 2.1 on 2019-02-27 14:03

import cashback_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback_app', '0037_auto_20190227_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'магазин', 'verbose_name_plural': 'магазины'},
        ),
        migrations.AddField(
            model_name='texts',
            name='referral_button_facebook',
            field=models.CharField(default='-', max_length=256, verbose_name='Приглашение в Facebook'),
        ),
        migrations.AddField(
            model_name='texts',
            name='referral_button_odnoklassniki',
            field=models.CharField(default='-', max_length=256, verbose_name='Приглашение в Одноклассники'),
        ),
        migrations.AddField(
            model_name='texts',
            name='referral_button_telegram',
            field=models.CharField(default='-', max_length=256, verbose_name='Приглашение в Telegram'),
        ),
        migrations.AddField(
            model_name='texts',
            name='referral_button_vkontakte',
            field=models.CharField(default='-', max_length=256, verbose_name='Приглашение Вконтакте'),
        ),
        migrations.AddField(
            model_name='texts',
            name='referral_invite_telegram_button',
            field=models.CharField(default='-', max_length=256, verbose_name='Кнопка приглашения в Telegram'),
        ),
        migrations.AddField(
            model_name='texts',
            name='referral_invite_telegram_message',
            field=models.TextField(default='-', verbose_name='Сообщение о приглашении в Telegram'),
        ),
        migrations.AddField(
            model_name='texts',
            name='referral_url_facebook',
            field=models.URLField(default='www.google.com', verbose_name='Ссылка Facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='texts',
            name='referral_url_odnoklassniki',
            field=models.URLField(default='www.google.com', verbose_name='Ссылка Одноклассники'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='texts',
            name='referral_url_vkontakte',
            field=models.URLField(default='www.google.com', verbose_name='Ссылка Вконтакте'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='categories',
            field=models.ManyToManyField(related_name='shops', to='cashback_app.Category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='command',
            field=models.CharField(max_length=64, verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='start_photo_0',
            field=cashback_app.models.Photo(blank=True, null=True, upload_to=cashback_app.models.Photo.get_path, validators=[cashback_app.models.Photo.validate_image], verbose_name='Фото #1'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='start_photo_1',
            field=cashback_app.models.Photo(blank=True, null=True, upload_to=cashback_app.models.Photo.get_path, validators=[cashback_app.models.Photo.validate_image], verbose_name='Фото #2'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='start_photo_2',
            field=cashback_app.models.Photo(blank=True, null=True, upload_to=cashback_app.models.Photo.get_path, validators=[cashback_app.models.Photo.validate_image], verbose_name='Фото #3'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='start_photo_3',
            field=cashback_app.models.Photo(blank=True, null=True, upload_to=cashback_app.models.Photo.get_path, validators=[cashback_app.models.Photo.validate_image], verbose_name='Фото #4'),
        ),
    ]
