# Generated by Django 2.1 on 2019-03-11 12:39

import cashback_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback_app', '0064_auto_20190310_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='my_title',
            field=models.CharField(default='-', max_length=256, verbose_name='Заголовок списка избранных магазинов'),
        ),
        migrations.AddField(
            model_name='texts',
            name='no_my',
            field=models.CharField(default='-', max_length=256, verbose_name='Список избранных магазинов пуст'),
        ),
        migrations.AddField(
            model_name='texts',
            name='search_title',
            field=models.CharField(default='-', max_length=256, verbose_name='Заголовок результатов поиска'),
        ),
        migrations.AddField(
            model_name='texts',
            name='shops_title',
            field=models.CharField(default='-', max_length=256, verbose_name='Заголовок списка магазинов'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=cashback_app.models.Photo(blank=True, null=True, upload_to=cashback_app.models.Photo.get_path, validators=[cashback_app.models.Photo.validate_image], verbose_name='Изображение, до 5МБ'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='photo',
            field=cashback_app.models.Photo(upload_to=cashback_app.models.Photo.get_path, validators=[cashback_app.models.Photo.validate_image], verbose_name='Фото программы'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='display_categories',
            field=models.TextField(default='-', max_length=256, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='start_photo_0',
            field=cashback_app.models.Photo(blank=True, null=True, upload_to=cashback_app.models.Photo.get_path, validators=[cashback_app.models.Photo.validate_image], verbose_name='Фото #1'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='start_photo_1',
            field=cashback_app.models.Photo(blank=True, null=True, upload_to=cashback_app.models.Photo.get_path, validators=[cashback_app.models.Photo.validate_image], verbose_name='Фото #2'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='start_photo_2',
            field=cashback_app.models.Photo(blank=True, null=True, upload_to=cashback_app.models.Photo.get_path, validators=[cashback_app.models.Photo.validate_image], verbose_name='Фото #3'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='start_photo_3',
            field=cashback_app.models.Photo(blank=True, null=True, upload_to=cashback_app.models.Photo.get_path, validators=[cashback_app.models.Photo.validate_image], verbose_name='Фото #4'),
        ),
    ]
