# Generated by Django 2.1 on 2019-03-21 13:22

import cashback_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback_app', '0095_auto_20190321_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='m_card',
            field=models.CharField(default='-', max_length=256, verbose_name='Ввод банковской карты'),
        ),
        migrations.AddField(
            model_name='texts',
            name='m_phone',
            field=models.CharField(default='-', max_length=256, verbose_name='Ввод телефона'),
        ),
        migrations.AddField(
            model_name='texts',
            name='m_qiwi',
            field=models.CharField(default='-', max_length=256, verbose_name='Ввод кошелька QIWI'),
        ),
        migrations.AddField(
            model_name='texts',
            name='m_yandex',
            field=models.CharField(default='-', max_length=256, verbose_name='Ввод кошелька Яндекс.Денег'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=cashback_app.models.Photo(blank=True, null=True, upload_to=cashback_app.models.Photo.get_path, validators=[cashback_app.models.Photo.validate_image], verbose_name='Изображение, до 5МБ'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='start_photo_0',
            field=cashback_app.models.Photo(blank=True, null=True, upload_to=cashback_app.models.Photo.get_path, validators=[cashback_app.models.Photo.validate_image], verbose_name='Фото #1'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='start_photo_1',
            field=cashback_app.models.Photo(blank=True, null=True, upload_to=cashback_app.models.Photo.get_path, validators=[cashback_app.models.Photo.validate_image], verbose_name='Фото #2'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='start_photo_2',
            field=cashback_app.models.Photo(blank=True, null=True, upload_to=cashback_app.models.Photo.get_path, validators=[cashback_app.models.Photo.validate_image], verbose_name='Фото #3'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='start_photo_3',
            field=cashback_app.models.Photo(blank=True, null=True, upload_to=cashback_app.models.Photo.get_path, validators=[cashback_app.models.Photo.validate_image], verbose_name='Фото #4'),
        ),
    ]
