"""
Django settings for cashback project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'm39tymk$d_5!rpe6a+(4m+sc7@363w+_(mfm70lg1a-lf#l&7z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['cashback-demo.lvadislav.com']

SITE_ID = 1

TOKEN = '740610593:AAHHt6OtI1d2TrkPfL4N0Y4AmP8-awuhhdo'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'admin_reorder',
    'django.contrib.staticfiles',
    'cashback_app',
    'preferences',
    'tickets',
    'django.contrib.sites',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cashback.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ADMIN_REORDER = (
    {'app': 'cashback_app',
    'label': 'Информация',
    'models': [
            {
                'model': 'cashback_app.User',
                'label': 'Пользователи'
            },
            {
                'model': 'cashback_app.Partner',
                'label': 'Партнеры'
            },
            {
                'model': 'cashback_app.Statistics',
                'label': 'Статистика'
            },
        ]
    },
    {'app': 'cashback_app',
    'label': 'Данные',
    'models': [
            {
                'model': 'cashback_app.Category',
                'label': 'Категории'
            },
            {
                'model': 'cashback_app.Shop',
                'label': 'Магазины'
            }
        ]
    },
    {
        'app': 'cashback_app',
        'label': 'Рассылка',
        'models': [
            {
                'model': 'cashback_app.Post',
                'label': 'Посты'
            },
        ]
    },
    {
        'app': 'tickets',
        'label': 'Поддержка',
        'models': [
            {
                'model': 'tickets.TicketDialogue',
                'label': 'Диалоги'
            },
        ]
    },
    {'app': 'cashback_app',
    'label': 'Настройки',
    'models': [
            {
                'model': 'cashback_app.Texts',
                'label': 'Тексты'
            },
            {
                'model': 'cashback_app.Financial',
                'label': 'Финансовые'
            },
        ]
    }
)

WSGI_APPLICATION = 'cashback.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# default static files settings for PythonAnywhere.
# see https://help.pythonanywhere.com/pages/DjangoStaticFiles for more info
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
STATIC_ROOT = STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'


ID = 1025052
CLIENT_ID = 'c1849e0b376385a0548a1f4e62cefb'
CLIENT_SECRET = '8dc7a2ef3084c22b33de8b690f6d9c'


TICKETS_SUPPORT_TITLE = f'Служба поддержки'
TICKETS_BOT_TOKEN = TOKEN
TICKETS_TO_USER = 'cashback_app.User'
TICKETS_TO_USER_URL_REVERSE = 'cashback_app_user'
TICKETS_MODULE_WITH_TELEBOT = 'cashback_app.handlers'
